### ISSUE TITLE
CI:  Failure to Checkout with Beta Package Added

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#2086]
Failure during [CI](https://github.com/alcionai/corso/actions/runs/3883931965/jobs/6626321063)
This could be related to memory in the CI or another issue. 

### Blocks

- #2069 
- #2071 
- #2084

**Comment by dadams39** [comment]
Blocker [Upstream-Graph-SDK-129](https://github.com/microsoftgraph/msgraph-sdk-go/issues/129)

**Comment by dadams39** [comment]
Temporarily, we can move in the two files from `Beta`. We will need to solve the problem of compilation with Beta to use the API for backups and restore.

**Comment by dadams39** [comment]
Suggestion from the comments is to increase the swap space on the runner:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
```

Need to verify if changes to the configuration will allow for the fix.
